# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aa493930ca09491cbb2d5e9028b6faf2"
name = "SKUs and Labels"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update"]
uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
